### ISSUE TITLE
Adicionar documentação

### ISSUE THREAD

**Issue by dherkyan** [eduardotsilva/clientes-api#1]
Adicionar documentação com as seguintes informações:

1. Visão geral do aplicativo;
2. Configurações necessárias;
3. Instruções sobre como executar a aplicação;

**Comment by eduardotsilva** [comment]
[Image]

Tá em construção kkk

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
From: Dherkyan Ribeiro ***@***.***>
Sent: Sunday, May 23, 2021 10:17:49 AM
To: eduardotsilva/clientes-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eduardotsilva/clientes-api] Adicionar documentação (#1)


Adicionar documentação com as seguintes informações:

  1.  Visão geral do aplicativo;
  2.  Configurações necessárias;
  3.  Instruções sobre como executar a aplicação;

**Comment by eduardotsilva** [comment]
> Adicionar documentação com as seguintes informações:
> 
> 1. Visão geral do aplicativo;
> 2. Configurações necessárias;
> 3. Instruções sobre como executar a aplicação;

Okay, estarei adicionando o README quanto antes.

**Comment by eduardotsilva** [comment]
Adicionado readme ao projeto

**Comment by eduardotsilva** [comment]
Adicionado readme ao projeto
