### ISSUE TITLE
Criar arquivos de profile dev e prod

### ISSUE THREAD

**Issue by dherkyan** [eduardotsilva/clientes-api#2]
Criar versão do arquivo **application.properties** para ambiente dev e prod.

definindo como **false**, no profile prod, as seguintes propriedades:
```spring.jpa.properties.hibernate.show_sql=true```
```spring.jpa.properties.hibernate.format_sql=true```

**Comment by eduardotsilva** [comment]
Issues resolvida no commit f54e732443f5e622e2c1ae342b0dcca7ed7dadd4
