### ISSUE TITLE
Configurar o path da aplicação

### ISSUE THREAD

**Issue by dherkyan** [eduardotsilva/clientes-api#4]
https://github.com/eduardotsilva/clientes-api/blob/459ea3a63090d55fe2f3d2ad8f7ef9105b8e8a7c/src/main/java/br/com/eduardo/clientes/rest/ClienteController.java#L14

Configurar o path da app via arquivo properties.

**Comment by eduardotsilva** [comment]
Atendida no commit 734ff54e7eb7d54aca9e435f5bb2b1f3c37c42d3
